ALTER SESSION SET CONTAINER = pdb;

DROP TABLESPACE scikey_data INCLUDING CONTENTS AND DATAFILES;

DROP TABLESPACE scikey_index INCLUDING CONTENTS AND DATAFILES;

DROP USER scikey CASCADE;

CREATE TABLESPACE scikey_data DATAFILE '/u01/app/oracle/oradata/SCIKEY/scikey_data01.dbf' SIZE 10G AUTOEXTEND ON NEXT 1G MAXSIZE 25G;

CREATE TABLESPACE scikey_index DATAFILE '/u01/app/oracle/oradata/SCIKEY/scikey_index01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 5G;

CREATE USER scikey IDENTIFIED BY scikeycosc416 DEFAULT TABLESPACE scikey_data TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON scikey_data QUOTA UNLIMITED ON scikey_index; 

GRANT CREATE SESSION TO scikey;
GRANT RESOURCE TO scikey;
GRANT CREATE VIEW TO scikey;
GRANT UNLIMITED TABLESPACE TO scikey;